ALTER TABLE productions ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE productions ADD COLUMN IF NOT EXISTS instagram VARCHAR(255);
ALTER TABLE productions ADD COLUMN IF NOT EXISTS website   VARCHAR(255);
